import nodemailer from "nodemailer";
import { logger } from "../lib/logger";
import { ComplaintData, generateComplaintPDF } from "./pdfGenerator";

const WARD_OFFICER_EMAILS: Record<string, string> = {
  "Ward 1": process.env["WARD1_EMAIL"] ?? "",
  "Ward 2": process.env["WARD2_EMAIL"] ?? "",
  "Ward 3": process.env["WARD3_EMAIL"] ?? "",
  default: process.env["DEFAULT_WARD_EMAIL"] ?? process.env["SMTP_FROM"] ?? "",
};

function getTransport() {
  if (process.env["SMTP_HOST"]) {
    return nodemailer.createTransport({
      host: process.env["SMTP_HOST"],
      port: parseInt(process.env["SMTP_PORT"] ?? "587", 10),
      secure: process.env["SMTP_SECURE"] === "true",
      auth: {
        user: process.env["SMTP_USER"],
        pass: process.env["SMTP_PASS"],
      },
    });
  }
  return nodemailer.createTransport({ jsonTransport: true });
}

export async function sendComplaintEmail(data: ComplaintData): Promise<boolean> {
  try {
    const pdf = generateComplaintPDF(data);
    const transport = getTransport();

    const wardEmail = (data.ward && WARD_OFFICER_EMAILS[data.ward]) || WARD_OFFICER_EMAILS["default"];
    const from = process.env["SMTP_FROM"] ?? "noreply@civix.app";

    const info = await transport.sendMail({
      from: `"Civix Platform" <${from}>`,
      to: wardEmail || from,
      subject: `[CIVIX] Community Complaint: ${data.title} — ${data.upvotes} Upvotes`,
      html: `
        <div style="font-family:sans-serif;max-width:600px;margin:0 auto;">
          <div style="background:#0f172a;padding:24px;border-radius:8px 8px 0 0;">
            <h1 style="color:white;margin:0;font-size:22px;">🏛️ Civix — Community Complaint</h1>
          </div>
          <div style="background:#f8fafc;padding:24px;border:1px solid #e2e8f0;border-top:none;border-radius:0 0 8px 8px;">
            <p style="color:#0f172a;font-size:16px;">A complaint has crossed the upvote threshold and requires your attention:</p>
            <table style="width:100%;border-collapse:collapse;margin:16px 0;">
              <tr><td style="padding:8px 0;color:#64748b;font-size:13px;">Issue</td><td style="padding:8px 0;color:#0f172a;font-weight:bold;">${data.title}</td></tr>
              <tr><td style="padding:8px 0;color:#64748b;font-size:13px;">Category</td><td style="padding:8px 0;color:#0f172a;">${data.category}</td></tr>
              <tr><td style="padding:8px 0;color:#64748b;font-size:13px;">Location</td><td style="padding:8px 0;color:#0f172a;">${data.location}</td></tr>
              <tr><td style="padding:8px 0;color:#64748b;font-size:13px;">Upvotes</td><td style="padding:8px 0;color:#10b981;font-weight:bold;">${data.upvotes}</td></tr>
            </table>
            <p style="color:#334155;">Please find the formal complaint letter attached as a PDF.</p>
            <p style="color:#64748b;font-size:12px;margin-top:24px;">This email was auto-generated by Civix when the complaint crossed the upvote threshold.</p>
          </div>
        </div>
      `,
      attachments: [
        {
          filename: `complaint-${data.issueId.slice(-8)}.pdf`,
          content: pdf,
          contentType: "application/pdf",
        },
      ],
    });

    logger.info({ issueId: data.issueId, ward: data.ward, info: info.messageId }, "Complaint email sent");
    return true;
  } catch (err) {
    logger.error({ err, issueId: data.issueId }, "Failed to send complaint email");
    return false;
  }
}
